apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: pricing-filter-wasme
  namespace: default
spec:
  selector:
    matchLabels:
      app: pricing
  pluginName: add_header
  url: oci://webassemblyhub.io/pheely/add-header:v0.2

