apiVersion: v1
kind: Service
metadata: 
  name: pricing
  labels:
    app: pricing
    service: pricing
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8002
  selector:
    app: pricing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing
  labels: 
    app: pricing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      labels:
        app: pricing
    spec:
      containers:
      - image: pheely/pricing:0.1
        imagePullPolicy: Always
        name: pricing
        ports: 
        - containerPort: 8002
