apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: pricing-filter-sdk
  namespace: default
spec:
  selector:
    matchLabels:
      app: pricing
  pluginName: add_header
  url: oci://pheely/mywasm:0.2
